// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: protos/clockwork/v1/entities.proto

package clockwork

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClockInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockInRequest) Reset() {
	*x = ClockInRequest{}
	mi := &file_protos_clockwork_v1_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInRequest) ProtoMessage() {}

func (x *ClockInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_clockwork_v1_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInRequest.ProtoReflect.Descriptor instead.
func (*ClockInRequest) Descriptor() ([]byte, []int) {
	return file_protos_clockwork_v1_entities_proto_rawDescGZIP(), []int{0}
}

type ClockInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockInResponse) Reset() {
	*x = ClockInResponse{}
	mi := &file_protos_clockwork_v1_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInResponse) ProtoMessage() {}

func (x *ClockInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_clockwork_v1_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInResponse.ProtoReflect.Descriptor instead.
func (*ClockInResponse) Descriptor() ([]byte, []int) {
	return file_protos_clockwork_v1_entities_proto_rawDescGZIP(), []int{1}
}

var File_protos_clockwork_v1_entities_proto protoreflect.FileDescriptor

var file_protos_clockwork_v1_entities_proto_rawDesc = string([]byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f,
	0x5a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f, 0x72, 0x6b, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_clockwork_v1_entities_proto_rawDescOnce sync.Once
	file_protos_clockwork_v1_entities_proto_rawDescData []byte
)

func file_protos_clockwork_v1_entities_proto_rawDescGZIP() []byte {
	file_protos_clockwork_v1_entities_proto_rawDescOnce.Do(func() {
		file_protos_clockwork_v1_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_clockwork_v1_entities_proto_rawDesc), len(file_protos_clockwork_v1_entities_proto_rawDesc)))
	})
	return file_protos_clockwork_v1_entities_proto_rawDescData
}

var file_protos_clockwork_v1_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_clockwork_v1_entities_proto_goTypes = []any{
	(*ClockInRequest)(nil),  // 0: protos.clockwork.v1.ClockInRequest
	(*ClockInResponse)(nil), // 1: protos.clockwork.v1.ClockInResponse
}
var file_protos_clockwork_v1_entities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_clockwork_v1_entities_proto_init() }
func file_protos_clockwork_v1_entities_proto_init() {
	if File_protos_clockwork_v1_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_clockwork_v1_entities_proto_rawDesc), len(file_protos_clockwork_v1_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_clockwork_v1_entities_proto_goTypes,
		DependencyIndexes: file_protos_clockwork_v1_entities_proto_depIdxs,
		MessageInfos:      file_protos_clockwork_v1_entities_proto_msgTypes,
	}.Build()
	File_protos_clockwork_v1_entities_proto = out.File
	file_protos_clockwork_v1_entities_proto_goTypes = nil
	file_protos_clockwork_v1_entities_proto_depIdxs = nil
}
